settings:
  serverName: root # 默认 root 用于区分子服
  reviveCooldown: 3600 #设置成0关闭，默认3600秒，复活时间，单位秒(重生冷却时间)
  messagePrefix: '&7[&a硬核模式&7] ' # 消息前缀
  useHardcoreHearts: true  # 是否使用极限模式爱心显示
  keepInventory: false # 是否保留物品
  
  reviveProcess: # 重生命令序列 {player} 代表玩家名
    - "tell {player} 重生成功！"
  # 将会按顺序执行，最后玩家会被调整为生存模式，因此无需在命令中设置
  # 这里可以是将玩家传送到主城/出生点的命令，总之插件会以 console 的身份运行你定义的命令
  
  reviveNeed: # 复活所需物品
    - playerpoints: 100 # 玩家点数，暂时只有这一项

  placeholderOnly: false # 仅占位符模式，插件不会实际执行复活逻辑

database:
  host: localhost # 数据库主机地址
  port: 3306 # 数据库端口
  name: dbName # 数据库名称
  username: userName # 数据库用户名
  password: userPassword # 数据库密码
  tablename: hardcoreData # 创建的数据表的名称
